//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBrake.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeBreak
    {
        public string Numero { get; set; }
        public bool Vegetariana { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
